
__all__ = [
    'quadraticl',
    'quadraticd',
    'quadratic',
    'quadraticf',
    "sinl", "sind", "sin", 'sinf', "asinl", 'asind', 'asin', 'asinf', 
    "cosl", "cosd", "cos", 'cosf', "acosl", 'acosd', 'acos', 'acosf', 
    "tanl", "tand", "tan", 'tanf', "atanl", 'atand', 'atan', 'atanf', 
    "cotl", "cotd", "cot", 'cotf', "acotl", 'acotd', 'acot', 'acotf', 
    "cscl", "cscd", "csc", 'cscf', "acscl", 'acscd', 'acsc', 'acscf', 
    "secl", "secd", "sec", 'secf', "asecl", 'asecd', 'asec', 'asecf', 
]

from gll.__common import *


def quadraticl(a:float, b:float, c:float) -> tuple[float,float]:
    """Quadratic formula
    [Created 3/10/20] cython // python 5/30/21 // cython 2/19/22"""
def quadraticd(a:float, b:float, c:float) -> tuple[float,float]:
    """Quadratic formula
    [Created 3/10/20] cython // python 5/30/21 // cython 2/19/22"""
def quadratic(a:float, b:float, c:float) -> tuple[float,float]:
    """Quadratic formula
    [Created 3/10/20] cython // python 5/30/21 // cython 2/19/22"""
def quadraticf(a:float, b:float, c:float) -> tuple[float,float]:
    """Quadratic formula
    [Created 3/10/20] cython // python 5/30/21 // cython 2/19/22"""



def  sinl(x:float) -> float: ...
def asinl(x:float) -> float: ...
def  sind(x:float) -> float: ...
def asind(x:float) -> float: ...
sin = math.sin
asin = math.asin
def  sinf(x:float) -> float: ...
def asinf(x:float) -> float: ...

def  cosl(x:float) -> float: ...
def acosl(x:float) -> float: ...
def  cosd(x:float) -> float: ...
def acosd(x:float) -> float: ...
cos = math.cos
acos = math.acos
def  cosf(x:float) -> float: ...
def acosf(x:float) -> float: ...

def  tanl(x:float) -> float: ...
def atanl(x:float) -> float: ...
def  tand(x:float) -> float: ...
def atand(x:float) -> float: ...
tan = math.tan
atan = math.atan
def  tanf(x:float) -> float: ...
def atanf(x:float) -> float: ...

def  cotl(x:float) -> float: ...
def acotl(x:float) -> float: ...
def  cotd(x:float) -> float: ...
def acotd(x:float) -> float: ...
def  cot (x:float) -> float: ...
def acot (x:float) -> float: ...
def  cotf(x:float) -> float: ...
def acotf(x:float) -> float: ...

def  cscl(x:float) -> float: ...
def acscl(x:float) -> float: ...
def  cscd(x:float) -> float: ...
def acscd(x:float) -> float: ...
def  csc (x:float) -> float: ...
def acsc (x:float) -> float: ...
def  cscf(x:float) -> float: ...
def acscf(x:float) -> float: ...

def  secl(x:float) -> float: ...
def asecl(x:float) -> float: ...
def  secd(x:float) -> float: ...
def asecd(x:float) -> float: ...
def  sec (x:float) -> float: ...
def asec (x:float) -> float: ...
def  secf(x:float) -> float: ...
def asecf(x:float) -> float: ...













